[bumpversion]
current_version = 0.1.0 # Specify the current version of your project, samne value as Cargo.toml version

# Specify how to search for and replace the version in the 'Cargo.toml' file.
[bumpversion:file:Cargo.toml]
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[bumpversion:file:README.toml]
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[bumpversion:file:README.md]
search  = '[![Version](https://img.shields.io/badge/Version-v{current_version}-green)](https://github.com/tamada/pick-a-boo/releases/tag/v{current_version})'
replace = '[![Version](https://img.shields.io/badge/Version-v{new_version}-green)](https://github.com/tamada/pick-a-boo/releases/tag/v{new_version})'
