name: publish_crate
on:
  push:
    tags:
      - "**"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4
      - name: build
        run: cargo build --release
      - name: Authenticate with custom registry
        id: auth
        uses: rust-lang/crates-io-auth-action@v1
      - name: Publish the crates
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run:
          cargo publish -p totebag
